
messages:
  reload-plugin: '&8[&5Elixirs&8] &aSuccessfully reloaded the plugin in &f{time}ms&a.'
  invalid-player: '&8[&5Elixirs&8] &7This player does not exist!'
  offline-player: '&8[&5Elixirs&8] &7Player &f{player} &7is offline.'
  invalid-elixir: '&8[&5Elixirs&8] &7Elixir &f{elixir} &7does not exist!'
  target-full-inventory: '&8[&5Elixirs&8] &7Player &f{player} &7has a full inventory! Dropping items on the ground.'


elixirs:
  fused:
    type: INSTANT_DAMAGE
    material: POTION
    splash: true
    data: 1
    display: '&dFused Elixir'
    lore:
      - '&7Used by warriors to destroy their'
      - '&7opponents in intense battles!'
      - ''
    effects:
      increase_damage:
        duration: 90
        amplifier: 1
      speed:
        duration: 90
        amplifier: 1
  aquatic:
    type: WATER_BREATHING
    material: POTION
    splash: false
    data: 1
    display: '&bAquatic Elixir'
    lore:
      - '&7Explore the sunken ruins with ease'
      - '&7while using this bizarre concoction.'
      - ''
    effects:
      water_breathing:
        duration: 1800
        amplifier: 0
